server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/api/v1/users/**

        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
          - Path=/api/v1/posts/**

        - id: DISCOVERY-SERVICE
          uri: http://localhost:8761/
          predicates:
          - Path=/eureka/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
